(function(){
  'use strict';
  const body=document.body, header=document.querySelector('.site-header'), navToggle=document.querySelector('.nav-toggle'), navMenu=document.querySelector('.nav-menu'), navLinks=document.querySelectorAll('.nav-link'), back=document.querySelector('.back-to-top');
  const setHeader=()=>{if(header) header.classList.toggle('is-scrolled',window.scrollY>20)}; window.addEventListener('scroll',setHeader,{passive:true}); setHeader();
  function closeNav(){if(!navToggle||!navMenu)return;navToggle.classList.remove('is-open');navMenu.classList.remove('is-open');navToggle.setAttribute('aria-expanded','false');body.classList.remove('no-scroll')}
  if(navToggle&&navMenu){navToggle.addEventListener('click',()=>{const open=navMenu.classList.contains('is-open');open?closeNav():(navToggle.classList.add('is-open'),navMenu.classList.add('is-open'),navToggle.setAttribute('aria-expanded','true'),body.classList.add('no-scroll'))});navLinks.forEach(a=>a.addEventListener('click',closeNav));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeNav()})}
  const current=location.pathname.split('/').pop()||'index.html'; navLinks.forEach(a=>{if((a.getAttribute('href')||'').split('/').pop()===current)a.classList.add('active')});
  const reveal=document.querySelectorAll('.reveal,.reveal-left,.reveal-right'); if('IntersectionObserver'in window){const io=new IntersectionObserver((entries,obs)=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');obs.unobserve(e.target)}})},{threshold:.12,rootMargin:'0px 0px -60px 0px'}); reveal.forEach((el,i)=>{el.style.transitionDelay=Math.min(i*40,240)+'ms';io.observe(el)})}else{reveal.forEach(el=>el.classList.add('is-visible'))}
  document.querySelectorAll('.faq-item').forEach((item,i)=>{const q=item.querySelector('.faq-question'), ans=item.querySelector('.faq-answer'); if(!q||!ans)return; q.setAttribute('aria-expanded','false'); q.addEventListener('click',()=>{const open=item.classList.contains('is-open'); document.querySelectorAll('.faq-item').forEach(other=>{if(other!==item){other.classList.remove('is-open');const a=other.querySelector('.faq-answer'),b=other.querySelector('.faq-question'); if(a)a.style.maxHeight='0px'; if(b)b.setAttribute('aria-expanded','false')}}); if(open){item.classList.remove('is-open');ans.style.maxHeight='0px';q.setAttribute('aria-expanded','false')}else{item.classList.add('is-open');ans.style.maxHeight=ans.scrollHeight+'px';q.setAttribute('aria-expanded','true')}})});
  const search=document.querySelector('[data-blog-search]'), cards=document.querySelectorAll('[data-blog-card]'), tabs=document.querySelectorAll('[data-category-filter]'), empty=document.querySelector('[data-blog-empty]'); let cat='all', term=''; function norm(v){return String(v||'').toLowerCase().trim()} function filter(){let count=0;cards.forEach(c=>{const okcat=cat==='all'||norm(c.dataset.category)===cat; const text=norm((c.dataset.title||'')+' '+(c.dataset.excerpt||'')+' '+(c.dataset.category||'')); const okterm=!term||text.includes(term); c.style.display=okcat&&okterm?'':'none'; if(okcat&&okterm)count++}); if(empty)empty.hidden=count!==0} if(search)search.addEventListener('input',e=>{term=norm(e.target.value);filter()}); tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');cat=norm(t.dataset.categoryFilter);filter()})); filter();
  if(back){const setBack=()=>back.classList.toggle('is-visible',window.scrollY>600);window.addEventListener('scroll',setBack,{passive:true});setBack();back.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}))}
  const prog=document.querySelector('[data-reading-progress]'); if(prog){const update=()=>{const h=document.documentElement.scrollHeight-innerHeight;prog.style.width=(h>0?Math.min(100,Math.max(0,scrollY/h*100)):0)+'%'};window.addEventListener('scroll',update,{passive:true});update()}
  const toc=document.querySelector('[data-toc]'), article=document.querySelector('.article-body'); if(toc&&article){article.querySelectorAll('h2,h3').forEach((h,i)=>{if(!h.id)h.id='section-'+(i+1);const a=document.createElement('a');a.href='#'+h.id;a.textContent=h.textContent;toc.appendChild(a)})}
  document.querySelectorAll('[data-current-year]').forEach(el=>el.textContent=new Date().getFullYear()); document.querySelectorAll('img').forEach(img=>{if(!img.loading)img.loading='lazy'; if(!img.decoding)img.decoding='async'});
})();